### ISSUE TITLE
Michaels problem.

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#12]
Michaels `dae_sim.py` problem overall is considerably difficult to solve. @mchlshort do you have the reference for this problem?.

Even with my finite_by_finite element approach. The solution of the simulation problem struggles.

I see that some `init_X.csv` and `init_Z.csv` files do all the magic.

Any ideas?

**Comment by mchlshort** [comment]
[Example – wavelength selection.pdf](https://github.com/dthierry/kipet/files/1896402/Example.wavelength.selection.pdf)

I have these couple slides as reference and I also have MATLAB and Ampl files for the problem. If you want me to I can e-mail these to you let me know. Not sure how useful they will be since they are for the MINLP model :/

**Comment by dthierry** [comment]
Ah, thanks @mchlshort. I will check the slides out.

**Comment by dthierry** [comment]
Sorry for the question but is the formulation in `dae_sim.py` correct? I mean according to the slides. Particularly the `rule_odes.`

**Comment by dthierry** [comment]
nvm I got it!
