### ISSUE TITLE
Ability to fit with concentration data where all species are not available at all times

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#128]
When I worked through Ex_7_concentration_input.py, it looks like at every time point where data is collected, we need to have the concentration of all the species. Is it possible to use data where not all species data are collected at all the points. This occurs frequently since we might be measure some species using an automated instrument and collect data more frequently vs another species that we manually sample and hence collect data less frequently

**Comment by kwmcbride** [comment]
Hello and thanks for pointing this out. This ability exists in Kipet at the moment, but unfortunately it is not in the ParameterEstimator module at this time. The current version of run_opt in ParameterEstimator does not account for missing component data (declared species without any data). I'll show you how to get this working by replacing a couple of lines in the code. I will submit this as a commit soon so that it is incorporated into the master branch.

The fix is to replace the rule_objective function on line 736 of ParameterEstimator with the following:

EDIT: There is a redundant loop that I need to remove!
```
        def rule_objective(m):
            obj=0
            if penaltyparamcon == True: #added for optional penalty term related to constraint CS
                rho = 100
                sumpen = 0.0
                for t, v in m.C.items():
                    k = t[1]
                    obj += 0.5*(m.C[t] - m.Z[t]) ** 2 / m.sigma[k]**2
                for t in m.allmeas_times:
                    sumpen += m.Y[t, 'npen']
                fifth_term = rho * sumpen
                obj += fifth_term
            else:
                for t, v in m.C.items():
                    k = t[1]
                    obj += 0.5*(m.C[t] - m.Z[t]) ** 2 / m.sigma[k]**2
            return obj
```
I recreated your error and got it to work by using the code above. This should be fixed pretty quickly.

**Comment by notesofdabbler** [comment]
Thanks for the suggested fix. I tried changing the ParameterEstimator.py per your suggestion and tried to reload the module in the code. But it seems to still be using the older version of ParameterEstimation.py. This is not related to Kipet but if you spot what I am doing wrong in reloading the module in this [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex7_concentration_input_noA_wk.ipynb), it will be very helpful.

**Comment by kwmcbride** [comment]
You need to change the module shown here if you want this to work (not in the local directory, unless you change your PYTHONPATH)
```
/opt/anaconda3/envs/kipetenv/lib/python3.7/site-packages/kipet-1.1.1-py3.7.egg/kipet/library/ParameterEstimator.py
```

Also, I changed the code slightly again, but it won't affect your example.

**Comment by notesofdabbler** [comment]
Sorry, my mistake. I just realized that I had modified the code in the kipet install that was outside of the conda environment kipetenv. Once I made the modification in the code that is within kipetenv, then it worked without error (I didn't have to use reload or specify PYTHONPATH).

**Comment by notesofdabbler** [comment]
I ran into an issue with the scenario which is a variation of the same example where A, B, C concentration are measured but at different frequencies. The dataset is in this [location](https://github.com/notesofdabbler/learn_kipet/blob/master/data_sets/Ex_1_C_data_irreg.txt) and the plot of data is below:
<img width="419" alt="Screen Shot 2020-07-25 at 3 44 29 PM" src="https://user-images.githubusercontent.com/7705554/88465096-16b72280-ce8e-11ea-9f86-5ab8300f75ad.png">

This dataset gave an error when reading using `read_concentration_data_txt(filename)`. I have created a variation [here](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex7_concentration_input_irregular_wk.ipynb) that works to read this data by putting `nan` for time points where concentration data is not available. Then I also had to make the following tweak to the code you had posted above where I excluded data points with `nan` from the objective function.

```
        def rule_objective(m):
            obj=0
            if penaltyparamcon == True: #added for optional penalty term related to constraint CS
                rho = 100
                sumpen = 0.0
                for t, v in m.C.items():
                    k = t[1]
                    if not np.isnan(value(v)):
                        obj += 0.5*(m.C[t] - m.Z[t]) ** 2 / m.sigma[k]**2
                for t in m.allmeas_times:
                    sumpen += m.Y[t, 'npen']
                fifth_term = rho * sumpen
                obj += fifth_term
            else:
                for t, v in m.C.items():
                    k = t[1]
                    if not np.isnan(value(v)):
                        obj += 0.5*(m.C[t] - m.Z[t]) ** 2 / m.sigma[k]**2
            return obj
```

With these changes, I get the following message when using `builder`:
```
Warning! Since {label}-matrix contains negative values Kipet is assuming a derivative of {label} has been inputted
```
But the code seems to run fine ([notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/Ex7_concentration_input_irregular_wk.ipynb)) and give the results.

It would be great if the ability to deal with such datasets is also added as a functionality since it is is common use case.

**Comment by kwmcbride** [comment]
I will look into this now. In the EstimationPotential module this problem does not exist.

**Comment by kwmcbride** [comment]
Okay, this was a little more involved than I thought, but I changed quite a few things in various modules to get this working. The issue was when you have multiple components _of the same type_ (such as several components or several complementary states) with different sample times. This has now been taken care of in TemplateBuilder, ResultsObject, and data_tools. There is now no need to handle nans in ParameterEstimator when generating the objective function.

I have to check if there are other spots where this may cause an issue and then I will make a pull request with the updates. Thanks for finding this!

**Comment by notesofdabbler** [comment]
Thanks for the latest update. I was working through the new example Ex7_concentration_heterogenous_data.py and it worked great.
