### ISSUE TITLE
Pyomo 5.7

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#131]
**The bug**
It seems that the way the Sets work has changed. This breaks core functionalities of kipet.

**To Reproduce**
Run any example

**Comment by kwmcbride** [comment]
I'll look into this soon. Hopefully this is not a big problem to change.

**Comment by kwmcbride** [comment]
I looked at the problem and it seems that Pyomo 5.7 does not like it when you have variables with empty sets. In TemplateBuilder all variables are initialized regardless of whether they are actually needed in the model.  I managed to get an example working after ignoring these empty sets and will now implement a cleaner approach and see if it works for the other examples.

I think this is actually a good thing. It forces us to make the code cleaner and may increase performance.

**Comment by kwmcbride** [comment]
I have fixed the Pyomo 5.7 issue. 

However, there is still something strange when using blocks to perform the multiple experiments estimation. There is a model component 'alltime_domain' that appears (I don't know where this comes from at the moment), and I get an error saying that it cannot be cloned because it already exists in the block. I simply check for this component and delete it if present. Then it works as expected. Any ideas as to what this could be?

I built this on top of the version in the pull request 144 and will wait until those changes are incorporated before making a new pull request.

**Comment by schenkch** [comment]
@kwmcbride: alltime was introduced with using measurements coming from different measurement techniques and incorporates all of them in one set. However, previously this feature was not included for the multiple experiments case yet.

**Comment by kwmcbride** [comment]
I mean the component 'alltime_domain'. I don't find it anywhere, but it shows up in the models anyway and the Block component doesn't like it because it can't clone it. I searched for it in the entire code and didn't find it, so I don't know where it is coming from or why it is there. It may be something Pyomo is doing in the background, but I wouldn't know why.

**Comment by dthierry** [comment]
I think `alltime_domain` is generated automatically in Pyomo 5.7. This should be the case with sets similar to `alltime`.

**Comment by kwmcbride** [comment]
I have added the updates for Pyomo 5.7 to the pull request "new_data".

The interesting thing is that I only get problems from alltime_domain. At the moment it does not seem to be necessary, but I don't like not knowing why.
