### ISSUE TITLE
syntax for estimating sensitivity to parameters

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#138]
Estimability Analyzer currently estimates sensitivity of concentrations to parameters. I was trying to directly use the function ```get_sensitivities_for_params``` to get the sensitivities (since sometimes these could be useful to review) using a simple first order reaction example ([notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/jbr_Sfirstorder.ipynb)). 
I found that the following way of initializing the parameter `k1` doesn't work and gives all values of sensitivity matrix as zero:
```
builder.add_parameter('k1', 1.0, bounds = (0.1, 10))
```
But explicitly setting initial value of `k1` the following way works:
```
opt_model.P['k1'].value = 1.0
```
Does that mean that we can't give an initial value to a parameter using add_parameter function?

**Comment by kwmcbride** [comment]
You need to use the keyword init:

builder.add_parameter('k1', init=1.0, bounds = (0.1, 10))

This works for me using your example without issue.

I looked at TemplateBuilder and it checks for kwargs with init. I can update it so that it checks for args as well so you don't need to write "init" everytime.

**Comment by notesofdabbler** [comment]
Thanks for the clarification. Using init worked.
