### ISSUE TITLE
read_file with directory seems to give an error

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#140]
The following way to read a file used to work previously but now gives an error.
```
filename = 'Ex_1_C_data.txt'
C_frame = read_file(filename, directory = '../data_sets')
```
But if I use the full path as below it works.
```
filename = '/home/paperspace/learn_kipet/data_sets/Ex_1_C_data.txt'
C_frame = read_file(filename)
```
This error is reproduced in this [notebook](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_examples/test_read_file.ipynb).

**Comment by kwmcbride** [comment]
That was a very brief change in the code and it has now been changed back to the original method for declaring the directory. This needed to be done because some of the tests no longer worked due to pointing towards the incorrect directory. It looks like this now:
```
dataDirectory = os.path.abspath(
        os.path.join( os.path.dirname( os.path.abspath( inspect.getfile(
            inspect.currentframe() ) ) ), 'data_sets'))
filename =  os.path.join(dataDirectory, 'Ex_1_C_data.txt')
```
This is another item on my list of things to change. I suspect it was set-up like this to make running the tests work alongside general use.

**Comment by notesofdabbler** [comment]
Thanks for the clarification
