### ISSUE TITLE
Error when using report functionality

### ISSUE THREAD

**Issue by notesofdabbler** [salvadorgarciamunoz/kipet#170]
I got the following error when trying to generate report in [Example 1](https://github.com/kwmcbride/kipet_examples/blob/master/examples/example_1/Ex_1_ode_sim.py). 
<img width="1144" alt="Screen Shot 2021-07-07 at 2 47 29 PM" src="https://user-images.githubusercontent.com/7705554/124813026-5efe1200-df32-11eb-8132-813c5e869c31.png">

The notebook with the full example is [here](https://github.com/notesofdabbler/learn_kipet/blob/master/kipet_pkg_examples/ex1_ode_sim_wk.ipynb).

**Comment by kwmcbride** [comment]
This error appears when using Jupyter notebooks. What happens is that the standard output file saving doesn't work when you use KIPET in this way. 

I could modify the code to ignore saving the log if it fails. I did not consider this important in a Juptyer notebook since the log is contained within the document already.

**Comment by kwmcbride** [comment]
I have fixed this error and will be updating KIPET shortly.

One thing that will not work is the file name. Since it is coming from a Jupyter notebook cell, it has a different location and naming convention. Thus, the file link is empty when using a Jupiter notebook to generate a report. You can also see these names in the chart files.
