### ISSUE TITLE
initial conditions for a simulation change mysteriously 

### ISSUE THREAD

**Issue by dthierry** [salvadorgarciamunoz/kipet#47]
After declaring the ics, and building the model; if a particular variable has initial condition of 0, it will set to 1.0 automatically for some reason.
This is particularly problematic for fe_factory.

**Comment by mchlshort** [comment]
I think that might be in TemplateBuilder. All z values are initialized at 1.

**Comment by dthierry** [comment]
Ah, I see. :| well that explains that. 
I've found that it does not matter for the *full* problem, because there is a constraint basically fixing this initial condition to the correct value. 
It should be fixed though. Is there a particular reason for the value of 1?

**Comment by mchlshort** [comment]
From what I can tell there is no particular reason. I would be reluctant to set it to 0 though as that can often lead to issues with solvers in my experience with large nlps... I am mostly familiar with conopt, though, so maybe ipopt is better suited to that? Also given that there is a non-negativity constraint on s, c and z, it might be a help to give a non-zero init in general for large-scale nlps, but perhaps fe-factory does not need that since it is not simultaneously optimising the full problem.

**Comment by mchlshort** [comment]
Hopefully the new TemplateBuilder in fe_factory_interface manages to fix this. 

If not, I think it may be a problem in the PyomoSimulator module. In the PyomoSimulator module the initializations of Z are re-written when the discretization is set. Since discretization happens only after the PyomoSimulator is called, these initializations are then the ones taken. 

Not sure if this was the exact problem going on for this issue, but if it is the function "_default_initialize" and "initialize_from_trajectory" will be the culprits.

**Comment by mchlshort** [comment]
This should be good now, with the latest merge of fe_factory_interface including the updated TemplateBuilder initializations for Z and the new estimation_with_C branch updating the inits for P
