### ISSUE TITLE
estimate the variances every time (this is really not an option in PE)

### ISSUE THREAD

**Issue by salvadorgarciamunoz** [salvadorgarciamunoz/kipet#73]

**Comment by mchlshort** [comment]
Looking through this again and going through the examples and code, I think that changing the current format is not necessary and may actually make the procedure too opaque. Running the VarianceEstimator separately from the ParameterEstimator makes sense mostly because of the number of options required in each function. Combining them results in an unnecessarily complicated and long function with too many potential options and will discourage ease of use. Advanced users may also find it useful to customize the functions and how they inter-link, specifically in how to initialize the ParameterEstimation (using scaling or not, for example). These are currently explained in the documentation. 

The variances can easily be estimated every time, with the inclusion of an extra 2 lines of code that I feel are actually necessary. We can perhaps re-visit this if users want a different approach.

**Comment by schenkch** [comment]
I totally agree with you in that point. That was something I was already thinking as well.
